app working

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,9 +1,9 @@
 branch="$(git rev-parse --abbrev-ref HEAD)"
 
-# if [ "$branch" = "main" ]; then
-#   echo "You can't commit directly to main branch"
-#   exit 1
-# fi
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
 
 # Lint staged files
 pnpm lint-staged
